apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemini-proxy
  template:
    metadata:
      labels:
        app: gemini-proxy
    spec:
      containers:
      - name: gemini-api
        image: gemini-proxy:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: api-key
---
apiVersion: v1
kind: Service
metadata:
  name: gemini-service
spec:
  type: NodePort
  selector:
    app: gemini-proxy
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
